import { create } from 'zustand'
import { immer } from 'zustand/middleware/immer'
import type { Expression, ViewState, ImageLayer } from '../types'
import type { StabilizerConfig } from '../features/brush/BrushStabilizer'

export type LabelDisplayMode = 'name-only' | 'coords-only' | 'both' | 'global'
export type VisibilityMode = 'function-labels' | 'points-only' | 'point-labels' | 'labels-only'
export type ShapeRenderMode = 'fill' | 'stroke' | 'both'

export interface GraphPoint {
  x: number
  y: number
  label: string
  latexLabel?: string // LaTeX formatted label for rendering
  symbolicX?: string // Symbolic form of x (e.g., "1/2", "sqrt(2)")
  symbolicY?: string // Symbolic form of y (e.g., "sqrt(15)")
  color?: string // Optional color for the point
  isAutoGenerated?: boolean // True if auto-generated from click detection
  expressionId?: string // If this point is from an expression, the expression ID
  labelOffset?: { x: number; y: number } // Custom label offset in pixels (screen coordinates)
  labelQuadrant?: number // Preferred quadrant (0-3) for label positioning
  customLabel?: string // User-edited label text (e.g., "P", "Q")
  customFullLabel?: string // Complete custom label (overrides all formatting, can include LaTeX)
  hideLabel?: boolean // If true, label is hidden but point remains visible
  labelDisplayMode?: LabelDisplayMode // Individual override for label display mode
}

interface DrawingStroke {
  id: string
  points: Array<{ x: number; y: number }> // Graph coordinates (changed from screen)
  color: string
  width: number
  tool: 'pen' | 'highlighter' | 'eraser'
  selected?: boolean
}

export interface TextObject {
  id: string
  text: string
  htmlContent?: string // Rich text HTML content (if present, use this instead of text)
  x: number // Graph x coordinate
  y: number // Graph y coordinate
  fontSize: number
  color: string
  selected?: boolean
  maxWidth?: number // Maximum width for text wrapping
}

// Geometry object types
export type GeometryObjectType = 'point' | 'segment' | 'line' | 'ray' | 'circle' | 'polygon'

// Detailed geometry tool types with subtypes
export type GeometryToolType =
  // Points
  | 'point-fixed'        // 고정점
  | 'point-slider'       // 끌개
  | 'point-midpoint'     // 중점
  // Lines
  | 'line-infinite'      // 직선
  | 'line-segment'       // 선분
  | 'line-ray'           // 반직선
  // Circles
  | 'circle-center-radius'   // 중심-반지름
  | 'circle-three-points'    // 세 점 지나는 원
  | 'circle-diameter'        // 지름으로 정의
  // Polygons
  | 'polygon-regular'        // 정다각형
  | 'polygon-parallelogram'  // 평행사변형
  | 'polygon-rhombus'        // 마름모
  | 'polygon-rectangle'      // 직사각형
  | 'polygon-square'         // 정사각형
  | 'polygon-kite'           // 연
  | 'polygon-right-triangle' // 직각삼각형
  // None
  | 'none'
  | 'select'

export interface GeometryPoint {
  x: number
  y: number
}

export interface GeometryObject {
  id: string
  type: GeometryObjectType
  subType?: GeometryToolType  // Detailed subtype
  label?: string
  color: string
  strokeWidth: number
  fillColor?: string
  visible: boolean
  selected: boolean
  scale?: number            // Scale factor for maintaining constant visual size

  // Dependency system
  dependencies?: string[]   // IDs of objects this object depends on
  dependents?: string[]     // IDs of objects that depend on this object

  // Type-specific properties
  points?: GeometryPoint[]  // For point, segment, line, ray, polygon

  // Slider-specific (for point-slider)
  sliderConfig?: {
    min: number
    max: number
    step: number
    value: number
    axis: 'x' | 'y'         // Direction of slider movement
  }

  // Point constraint (for points on lines, circles, polygons)
  constraint?: {
    objectId: string        // ID of the object this point is constrained to
    type: 'line' | 'circle' | 'polygon'
    // For lines: t parameter (0-1 for segments, any value for infinite lines/rays)
    // For circles: angle in radians
    // For polygons: { edgeIndex, t } - which edge and position on that edge
    param?: number | { edgeIndex: number; t: number }
  }

  // Midpoint/division point ratio (for point-midpoint)
  ratio?: {
    m: number               // First ratio value
    n: number               // Second ratio value
  }

  // Line-specific
  linePoints?: {
    point1Id: string        // Start point ID
    point2Id: string        // End/direction point ID
  }

  // Circle-specific
  circleConfig?: {
    centerId?: string           // Center point ID
    radiusPointId?: string      // Radius-defining point ID
    point1Id?: string           // Three-point circle: first point
    point2Id?: string           // Three-point/diameter circle: second point
    point3Id?: string           // Three-point circle: third point
  }
  center?: GeometryPoint    // For circle
  radius?: number           // For circle
  point1?: GeometryPoint    // For line/ray (starting point)
  point2?: GeometryPoint    // For line/ray (direction point)

  // Polygon-specific (for polygon-regular)
  sides?: number            // Number of sides for regular polygons
}

interface HistoryState {
  expressions: Expression[]
  graphPoints: GraphPoint[]
  images: ImageLayer[]
  drawings: DrawingStroke[]
  textObjects: TextObject[]
  geometryObjects: GeometryObject[]
  view: ViewState
  pages: Page[]
  currentPageIndex: number
}

export interface Page {
  id: string
  name: string
  expressions: Expression[]
  graphPoints: GraphPoint[]
  images: ImageLayer[]
  drawings: DrawingStroke[]
  textObjects: TextObject[]
  geometryObjects: GeometryObject[]
  view: ViewState
  thumbnail?: string // Data URL of page preview
}

interface AppState {
  // Panel tabs
  activePanelTab: 'expression' | 'geometry' | 'page' | 'brush'
  setActivePanelTab: (tab: 'expression' | 'geometry' | 'page' | 'brush') => void

  // Expressions
  expressions: Expression[]
  addExpression: (expr: Omit<Expression, 'id'>) => void
  insertExpression: (expr: Omit<Expression, 'id'>, afterIndex: number) => void
  updateExpression: (id: string, updates: Partial<Expression>) => void
  removeExpression: (id: string) => void
  deselectAllExpressions: () => void

  // Graph points (intersections, intercepts)
  graphPoints: GraphPoint[]
  addGraphPoint: (point: Omit<GraphPoint, 'label'>) => void
  removeGraphPoint: (index: number) => void
  clearGraphPoints: () => void
  updateGraphPointLabel: (index: number, labelOffset: { x: number; y: number }) => void
  updateGraphPoint: (index: number, updates: Partial<GraphPoint>) => void
  globalLabelDisplayMode: LabelDisplayMode
  setGlobalLabelDisplayMode: (mode: LabelDisplayMode) => void
  showFunctionLabels: boolean
  toggleFunctionLabels: () => void

  // View state
  view: ViewState
  setView: (view: Partial<ViewState>) => void
  zoom: (factor: number, centerX?: number, centerY?: number) => void
  zoomAxis: (axis: 'x' | 'y', factor: number) => void
  pan: (dx: number, dy: number) => void
  resetView: () => void
  gridMode: 'grid' | 'grid-axis' | 'axis' | 'none'
  toggleGridMode: () => void
  setGridMode: (mode: 'grid' | 'grid-axis' | 'axis' | 'none') => void
  visibilityMode: VisibilityMode
  setVisibilityMode: (mode: VisibilityMode) => void
  pointVisibilityMode: 'hide' | 'show' | 'show-with-labels'
  setPointVisibilityMode: (mode: 'hide' | 'show' | 'show-with-labels') => void
  shapeRenderMode: ShapeRenderMode
  setShapeRenderMode: (mode: ShapeRenderMode) => void

  // Image layers
  images: ImageLayer[]
  addImage: (image: Omit<ImageLayer, 'id'>) => void
  updateImage: (id: string, updates: Partial<ImageLayer>) => void
  removeImage: (id: string) => void

  // Drawing tools
  drawings: DrawingStroke[]
  addDrawing: (stroke: Omit<DrawingStroke, 'id'>) => void
  removeDrawing: (id: string) => void
  updateDrawing: (id: string, updates: Partial<Omit<DrawingStroke, 'id'>>) => void
  clearDrawings: () => void
  clearAll: () => void
  drawingTool: 'none' | 'pen' | 'highlighter' | 'eraser' | 'select' | 'text'
  setDrawingTool: (tool: 'none' | 'pen' | 'highlighter' | 'eraser' | 'select' | 'text') => void
  penColor: string
  setPenColor: (color: string) => void
  highlighterColor: string
  setHighlighterColor: (color: string) => void
  penThickness: number
  setPenThickness: (thickness: number) => void
  highlighterThickness: number
  setHighlighterThickness: (thickness: number) => void
  eraserThickness: number
  setEraserThickness: (thickness: number) => void
  colorHistory: string[]
  addToColorHistory: (color: string) => void
  brushStabilizer: StabilizerConfig
  setBrushStabilizer: (config: Partial<StabilizerConfig>) => void

  // Text objects
  textObjects: TextObject[]
  addTextObject: (text: Omit<TextObject, 'id'>) => void
  removeTextObject: (id: string) => void
  updateTextObject: (id: string, updates: Partial<Omit<TextObject, 'id'>>) => void
  clearTextObjects: () => void

  // Geometry objects
  geometryObjects: GeometryObject[]
  addGeometryObject: (obj: Omit<GeometryObject, 'id'>) => string
  updateGeometryObject: (id: string, updates: Partial<GeometryObject>) => void
  removeGeometryObject: (id: string) => void
  clearGeometryObjects: () => void
  geometryTool: GeometryObjectType | 'none' | 'select'
  setGeometryTool: (tool: GeometryObjectType | 'none' | 'select') => void

  // Selection state for geometry and drawing objects
  selectedIds: string[]
  setSelectedIds: (ids: string[]) => void

  // Geometry submenu
  geometrySubMenu: {
    visible: boolean
    toolType: 'point' | 'line' | 'circle' | null
  }
  setGeometrySubMenu: (menu: { visible: boolean; toolType: 'point' | 'line' | 'circle' | null }) => void

  // Geometry creation state
  creationState: {
    active: boolean
    toolType: GeometryToolType
    step: number
    tempPoints: string[]
    preview?: any
  }
  setCreationState: (state: Partial<AppState['creationState']>) => void
  startCreation: (toolType: GeometryToolType) => void
  addCreationPoint: (pointId: string) => void
  finishCreation: () => void
  cancelCreation: () => void

  // Regular polygon dialog
  regularPolygonDialog: {
    visible: boolean
    centerPointId: string | null
    radiusPointId: string | null
    sides: number
  }
  setRegularPolygonDialog: (state: Partial<AppState['regularPolygonDialog']>) => void
  closeRegularPolygonDialog: () => void

  // History for undo/redo
  history: HistoryState[]
  historyIndex: number
  undo: () => void
  redo: () => void
  canUndo: () => boolean
  canRedo: () => boolean
  saveToHistory: () => void // Manually save current state to history

  // Pages
  pages: Page[]
  currentPageIndex: number
  addPage: () => void
  removePage: (index: number) => void
  switchPage: (index: number) => void
  updatePageName: (index: number, name: string) => void
  reorderPages: (fromIndex: number, toIndex: number) => void
  updatePageThumbnail: (index: number, thumbnail: string) => void
}

const PRESET_COLORS = [
  '#2c2c2c', '#0000ff', '#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4',
  '#ffeaa7', '#dfe6e9', '#a29bfe', '#fd79a8', '#fdcb6e', '#6c5ce7',
]

// Pastel colors for shape fills (rotating)
export const PASTEL_COLORS = [
  '#B4D4FF',  // Light blue
  '#FFB4D4',  // Light pink
  '#B4FFD4',  // Light green
  '#FFE4B4',  // Light yellow
  '#D4B4FF',  // Light purple
]

export const useStore = create<AppState>()(
  immer((set) => ({
    // Initial state
    activePanelTab: 'expression' as 'expression' | 'geometry' | 'page' | 'brush',

    expressions: [
      {
        id: crypto.randomUUID(),
        kind: 'cartesian',
        input: '',
        latex: '',
        color: PRESET_COLORS[0],
        visible: true,
        selected: false,
      }
    ],
    graphPoints: [],
    globalLabelDisplayMode: 'both',
    showFunctionLabels: true,
    view: {
      center: { x: 0, y: 0 },
      scale: 50, // pixels per unit
      scaleX: 1, // X-axis scale multiplier
      scaleY: 1, // Y-axis scale multiplier
      grid: true,
      axis: true,
    },
    gridMode: 'grid' as 'grid' | 'grid-axis' | 'axis' | 'none',
    visibilityMode: 'point-labels' as VisibilityMode,
    pointVisibilityMode: 'show-with-labels' as 'hide' | 'show' | 'show-with-labels',
    shapeRenderMode: 'both' as ShapeRenderMode,
    images: [],
    drawings: [],
    textObjects: [],
    drawingTool: 'none',
    penColor: '#2c2c2c',
    highlighterColor: '#ff9900',
    penThickness: 2,
    highlighterThickness: 10,
    eraserThickness: 20,
    colorHistory: [],
    brushStabilizer: {
      mode: 'weighted',
      queueSize: 10,
      delayDistance: 10,
      finishStabilizer: true,
      stabilizeSensors: true,
      zoomLevel: 1.0,
    },
    geometryObjects: [],
    geometryTool: 'none',
    selectedIds: [],

    geometrySubMenu: {
      visible: false,
      toolType: null,
    },

    creationState: {
      active: false,
      toolType: 'none',
      step: 0,
      tempPoints: [],
      preview: undefined,
    },

    regularPolygonDialog: {
      visible: false,
      centerPointId: null,
      radiusPointId: null,
      sides: 3,
    },

    history: [{
      expressions: [{
        id: crypto.randomUUID(),
        kind: 'cartesian',
        input: '',
        latex: '',
        color: PRESET_COLORS[0],
        visible: true,
        selected: false,
      }],
      graphPoints: [],
      images: [],
      drawings: [],
      textObjects: [],
      geometryObjects: [],
      view: {
        center: { x: 0, y: 0 },
        scale: 50,
        scaleX: 1,
        scaleY: 1,
        grid: true,
        axis: true,
      },
      pages: [{
        id: crypto.randomUUID(),
        name: '페이지 1',
        expressions: [{
          id: crypto.randomUUID(),
          kind: 'cartesian',
          input: '',
          latex: '',
          color: PRESET_COLORS[0],
          visible: true,
          selected: false,
        }],
        graphPoints: [],
        images: [],
        drawings: [],
        textObjects: [],
        geometryObjects: [],
        view: {
          center: { x: 0, y: 0 },
          scale: 50,
          scaleX: 1,
          scaleY: 1,
          grid: true,
          axis: true,
        },
      }],
      currentPageIndex: 0,
    }],
    historyIndex: 0,

    // Pages - start with one default page
    pages: [{
      id: crypto.randomUUID(),
      name: '페이지 1',
      expressions: [{
        id: crypto.randomUUID(),
        kind: 'cartesian',
        input: '',
        latex: '',
        color: PRESET_COLORS[0],
        visible: true,
        selected: false,
      }],
      graphPoints: [],
      images: [],
      drawings: [],
      textObjects: [],
      geometryObjects: [],
      view: {
        center: { x: 0, y: 0 },
        scale: 50,
        scaleX: 1,
        scaleY: 1,
        grid: true,
        axis: true,
      },
    }],
    currentPageIndex: 0,

    // Panel tab actions
    setActivePanelTab: (tab) => set((state) => {
      state.activePanelTab = tab
    }),

    // Expression actions
    addExpression: (expr) => set((state) => {
      state.expressions.push({
        ...expr,
        id: crypto.randomUUID(),
      })
    }),

    insertExpression: (expr, afterIndex) => set((state) => {
      const newExpr = {
        ...expr,
        id: crypto.randomUUID(),
      }
      // Insert after the specified index
      state.expressions.splice(afterIndex + 1, 0, newExpr)
    }),

    updateExpression: (id, updates) => set((state) => {
      const index = state.expressions.findIndex(e => e.id === id)
      if (index !== -1) {
        state.expressions[index] = { ...state.expressions[index], ...updates }
      }
    }),

    removeExpression: (id) => set((state) => {
      state.expressions = state.expressions.filter(e => e.id !== id)
    }),

    deselectAllExpressions: () => set((state) => {
      state.expressions.forEach(expr => {
        expr.selected = false
      })
    }),

    // Graph point actions
    addGraphPoint: (point) => set((state) => {
      // Only snap if symbolic values are not provided
      const snappedX = point.symbolicX ? point.x : snapToSpecialValue(point.x)
      const snappedY = point.symbolicY ? point.y : snapToSpecialValue(point.y)

      // Check if this is the origin (0, 0)
      const isOrigin = Math.abs(snappedX) < 1e-10 && Math.abs(snappedY) < 1e-10

      // Generate label: O for origin, otherwise A, B, C, ..., Z, AA, AB, ...
      const index = state.graphPoints.length
      const nameLabel = isOrigin ? 'O' : indexToLabel(index)
      const coordLabel = `(${formatCoord(snappedX)}, ${formatCoord(snappedY)})`
      const latexCoordLabel = `\\left(${formatCoordLatex(snappedX)}, ${formatCoordLatex(snappedY)}\\right)`

      state.graphPoints.push({
        ...point,
        x: snappedX,
        y: snappedY,
        label: `${nameLabel}${coordLabel}`,
        latexLabel: `${nameLabel}${latexCoordLabel}`,
        customLabel: nameLabel // Store alphabet name separately
      })

      // Save state to history after making changes
      saveHistory(state)
    }),

    removeGraphPoint: (index) => set((state) => {
      state.graphPoints.splice(index, 1)
      // Regenerate labels for all remaining points
      state.graphPoints.forEach((point, i) => {
        // Check if this is the origin (0, 0)
        const isOrigin = Math.abs(point.x) < 1e-10 && Math.abs(point.y) < 1e-10
        const nameLabel = isOrigin ? 'O' : indexToLabel(i)

        // Use symbolic forms if available, otherwise format as numbers
        const xStr = point.symbolicX || formatCoordLatex(point.x)
        const yStr = point.symbolicY || formatCoordLatex(point.y)

        const coordLabel = `(${formatCoord(point.x)}, ${formatCoord(point.y)})`
        const latexCoordLabel = `\\left(${xStr}, ${yStr}\\right)`
        point.label = `${nameLabel}${coordLabel}`
        point.latexLabel = `${nameLabel}${latexCoordLabel}`
        point.customLabel = nameLabel // Update alphabet name
      })

      // Save state to history after making changes
      saveHistory(state)
    }),

    clearGraphPoints: () => set((state) => {
      state.graphPoints = []

      // Save state to history after making changes
      saveHistory(state)
    }),

    updateGraphPointLabel: (index, labelOffset) => set((state) => {
      if (index >= 0 && index < state.graphPoints.length) {
        state.graphPoints[index].labelOffset = labelOffset
      }
    }),

    updateGraphPoint: (index, updates) => set((state) => {
      if (index >= 0 && index < state.graphPoints.length) {
        Object.assign(state.graphPoints[index], updates)
      }
    }),

    setGlobalLabelDisplayMode: (mode) => set((state) => {
      state.globalLabelDisplayMode = mode
    }),

    toggleFunctionLabels: () => set((state) => {
      state.showFunctionLabels = !state.showFunctionLabels
    }),

    // View actions
    setView: (view) => set((state) => {
      state.view = { ...state.view, ...view }
    }),

    zoom: (factor, centerX, centerY) => set((state) => {
      state.view.scale = state.view.scale * factor

      // Also zoom images (screen coordinates) around the zoom center
      if (centerX !== undefined && centerY !== undefined) {
        state.images.forEach(image => {
          // Skip if image doesn't have transform
          if (!image.transform) return

          // Calculate vector from zoom center to image center
          const dx = image.transform.e - centerX
          const dy = image.transform.f - centerY

          // Scale position relative to zoom center
          image.transform.e = centerX + dx * factor
          image.transform.f = centerY + dy * factor

          // Scale image size
          image.transform.a *= factor
          image.transform.d *= factor
        })
      }

      // Save state to history after making changes
      saveHistory(state)
    }),

    pan: (dx, dy) => set((state) => {
      state.view.center.x += dx
      state.view.center.y += dy

      // Note: Drawing points are stored in graph coordinates,
      // so they automatically move with the view. No need to adjust them.

      // Move images with legacy transform (screen coordinates)
      // Only needed for images without graphPosition
      const screenDx = -dx * state.view.scale * state.view.scaleX
      const screenDy = dy * state.view.scale * state.view.scaleY

      state.images.forEach(image => {
        // Only move legacy transform, graphPosition-based images move automatically
        if (!image.graphPosition) {
          image.transform.e += screenDx
          image.transform.f += screenDy
        }
      })

      // Save state to history after making changes
      saveHistory(state)
    }),

    zoomAxis: (axis, factor) => set((state) => {
      if (axis === 'x') {
        state.view.scaleX = state.view.scaleX * factor
      } else {
        state.view.scaleY = state.view.scaleY * factor
      }

      // Save state to history after making changes
      saveHistory(state)
    }),

    resetView: () => set((state) => {
      // Simply reset viewport and zoom to initial values
      // Don't move images or drawings - they are in graph coordinates
      state.view.center = { x: 0, y: 0 }
      state.view.scale = 50
      state.view.scaleX = 1
      state.view.scaleY = 1
    }),

    toggleGridMode: () => set((state) => {
      const modes: Array<'grid' | 'grid-axis' | 'axis' | 'none'> = ['grid', 'grid-axis', 'axis', 'none']
      const currentIndex = modes.indexOf(state.gridMode)
      state.gridMode = modes[(currentIndex + 1) % modes.length]
    }),

    setGridMode: (mode) => set((state) => {
      state.gridMode = mode
    }),

    setVisibilityMode: (mode) => set((state) => {
      state.visibilityMode = mode
    }),

    setPointVisibilityMode: (mode) => set((state) => {
      state.pointVisibilityMode = mode
    }),

    setShapeRenderMode: (mode) => set((state) => {
      state.shapeRenderMode = mode
    }),

    // Image actions
    addImage: (image) => {
      const newId = crypto.randomUUID()
      set((state) => {
        state.images.push({
          ...image,
          id: newId,
        })

        // Save state to history after making changes
        saveHistory(state)
      })
      return newId
    },

    updateImage: (id, updates) => set((state) => {
      const index = state.images.findIndex(img => img.id === id)
      if (index !== -1) {
        state.images[index] = { ...state.images[index], ...updates }
      }

      // Save state to history after making changes
      saveHistory(state)
    }),

    removeImage: (id) => set((state) => {
      state.images = state.images.filter(img => img.id !== id)

      // Save state to history after making changes
      saveHistory(state)
    }),

    // Drawing actions
    addDrawing: (stroke) => {
      const newId = crypto.randomUUID()
      set((state) => {
        state.drawings.push({
          ...stroke,
          id: newId,
        })

        // Save state to history after making changes
        saveHistory(state)
      })
      return newId
    },

    removeDrawing: (id) => set((state) => {
      state.drawings = state.drawings.filter(drawing => drawing.id !== id)

      // Save state to history after making changes
      saveHistory(state)
    }),

    updateDrawing: (id, updates) => set((state) => {
      const drawing = state.drawings.find(d => d.id === id)
      if (drawing) {
        Object.assign(drawing, updates)
      }
      // Note: No history save here to avoid performance issues during drag
    }),

    clearDrawings: () => set((state) => {
      state.drawings = []

      // Save state to history after making changes
      saveHistory(state)
    }),

    // Text object actions
    addTextObject: (text) => {
      const newId = crypto.randomUUID()
      set((state) => {
        state.textObjects.push({
          id: newId,
          ...text
        })

        // Save state to history after making changes
        saveHistory(state)
      })
      return newId
    },

    removeTextObject: (id) => set((state) => {
      state.textObjects = state.textObjects.filter(text => text.id !== id)

      // Save state to history after making changes
      saveHistory(state)
    }),

    updateTextObject: (id, updates) => set((state) => {
      const text = state.textObjects.find(t => t.id === id)
      if (text) {
        Object.assign(text, updates)
      }
    }),

    clearTextObjects: () => set((state) => {
      state.textObjects = []

      // Save state to history after making changes
      saveHistory(state)
    }),

    clearAll: () => set((state) => {
      state.drawings = []
      state.textObjects = []
      state.graphPoints = []
      state.images = []
      state.geometryObjects = []

      // Save state to history after making changes (only once!)
      saveHistory(state)
    }),

    setDrawingTool: (tool) => set((state) => {
      // If turning off select tool, clear all selections
      if (state.drawingTool === 'select' && tool !== 'select') {
        state.expressions.forEach(e => {
          if (e.selected) {
            e.selected = false
          }
        })
        state.drawings.forEach(s => {
          if (s.selected) {
            s.selected = false
          }
        })
        state.images.forEach(img => {
          if (img.selected) {
            img.selected = false
          }
        })
      }
      state.drawingTool = tool
    }),

    setPenColor: (color) => set((state) => {
      state.penColor = color
      // Add to color history
      if (!state.colorHistory.includes(color)) {
        state.colorHistory.unshift(color)
        // Keep only last 10 colors
        if (state.colorHistory.length > 10) {
          state.colorHistory = state.colorHistory.slice(0, 10)
        }
      } else {
        // Move to front if already exists
        state.colorHistory = [color, ...state.colorHistory.filter(c => c !== color)]
      }
    }),

    setHighlighterColor: (color) => set((state) => {
      state.highlighterColor = color
      // Add to color history
      if (!state.colorHistory.includes(color)) {
        state.colorHistory.unshift(color)
        // Keep only last 10 colors
        if (state.colorHistory.length > 10) {
          state.colorHistory = state.colorHistory.slice(0, 10)
        }
      } else {
        // Move to front if already exists
        state.colorHistory = [color, ...state.colorHistory.filter(c => c !== color)]
      }
    }),

    setPenThickness: (thickness) => set((state) => {
      state.penThickness = thickness
    }),

    setHighlighterThickness: (thickness) => set((state) => {
      state.highlighterThickness = thickness
    }),

    setEraserThickness: (thickness) => set((state) => {
      state.eraserThickness = thickness
    }),

    addToColorHistory: (color) => set((state) => {
      if (!state.colorHistory.includes(color)) {
        state.colorHistory.unshift(color)
        // Keep only last 10 colors
        if (state.colorHistory.length > 10) {
          state.colorHistory = state.colorHistory.slice(0, 10)
        }
      } else {
        // Move to front if already exists
        state.colorHistory = [color, ...state.colorHistory.filter(c => c !== color)]
      }
    }),

    setBrushStabilizer: (config) => set((state) => {
      state.brushStabilizer = { ...state.brushStabilizer, ...config }
    }),

    // Geometry object actions
    addGeometryObject: (obj) => {
      const newId = crypto.randomUUID()
      set((state) => {
        state.geometryObjects.push({
          ...obj,
          id: newId,
        })

        // Save state to history after making changes
        saveHistory(state)
      })
      return newId
    },

    updateGeometryObject: (id, updates) => set((state) => {
      const index = state.geometryObjects.findIndex(obj => obj.id === id)
      if (index !== -1) {
        state.geometryObjects[index] = { ...state.geometryObjects[index], ...updates }
      }

      // Save state to history after making changes
      saveHistory(state)
    }),

    removeGeometryObject: (id) => set((state) => {
      const objToRemove = state.geometryObjects.find(obj => obj.id === id)
      if (!objToRemove) return

      // Collect IDs to remove (object + its exclusive dependencies)
      const idsToRemove: string[] = [id]

      // If this object has dependencies (points that define it), check if they should be removed too
      if (objToRemove.dependencies && objToRemove.dependencies.length > 0) {
        objToRemove.dependencies.forEach(depId => {
          const depObj = state.geometryObjects.find(obj => obj.id === depId)
          if (!depObj) return

          // Check if this dependency is used by other objects
          const isUsedByOthers = state.geometryObjects.some(obj =>
            obj.id !== id && // Not the object being removed
            (
              (obj.dependencies && obj.dependencies.includes(depId)) || // Used as dependency
              (obj.linePoints && (obj.linePoints.point1Id === depId || obj.linePoints.point2Id === depId)) // Used as line point
            )
          )

          // Only remove if not used by other objects
          if (!isUsedByOthers) {
            idsToRemove.push(depId)
          } else {
            // If used by others, just remove this object from the dependency's dependents list
            if (depObj.dependents) {
              depObj.dependents = depObj.dependents.filter(d => d !== id)
            }
          }
        })
      }

      // Also check linePoints for lines/segments/rays
      if (objToRemove.linePoints) {
        const { point1Id, point2Id } = objToRemove.linePoints

        ;[point1Id, point2Id].forEach(pointId => {
          const pointObj = state.geometryObjects.find(obj => obj.id === pointId)
          if (!pointObj) return

          // Check if this point is used by other objects
          const isUsedByOthers = state.geometryObjects.some(obj =>
            obj.id !== id && // Not the object being removed
            (
              (obj.dependencies && obj.dependencies.includes(pointId)) || // Used as dependency
              (obj.linePoints && (obj.linePoints.point1Id === pointId || obj.linePoints.point2Id === pointId)) // Used as line point
            )
          )

          // Only remove if not used by other objects
          if (!isUsedByOthers) {
            idsToRemove.push(pointId)
          } else {
            // If used by others, just remove this object from the point's dependents list
            if (pointObj.dependents) {
              pointObj.dependents = pointObj.dependents.filter(d => d !== id)
            }
          }
        })
      }

      // Remove all collected IDs
      state.geometryObjects = state.geometryObjects.filter(obj => !idsToRemove.includes(obj.id))

      // Save state to history after making changes
      saveHistory(state)
    }),

    clearGeometryObjects: () => set((state) => {
      state.geometryObjects = []

      // Save state to history after making changes
      saveHistory(state)
    }),

    setGeometryTool: (tool) => set((state) => {
      // If turning off select tool, clear all selections
      if (state.geometryTool === 'select' && tool !== 'select') {
        state.geometryObjects.forEach(obj => {
          if (obj.selected) {
            obj.selected = false
          }
        })
      }
      state.geometryTool = tool
    }),

    setSelectedIds: (ids) => set((state) => {
      state.selectedIds = ids
    }),

    setGeometrySubMenu: (menu) => set((state) => {
      state.geometrySubMenu = menu
    }),

    setCreationState: (updates) => set((state) => {
      state.creationState = { ...state.creationState, ...updates }
    }),

    startCreation: (toolType) => set((state) => {
      state.creationState = {
        active: true,
        toolType,
        step: 0,
        tempPoints: [],
        preview: undefined,
      }
    }),

    addCreationPoint: (pointId) => set((state) => {
      state.creationState.tempPoints.push(pointId)
      state.creationState.step++
    }),

    finishCreation: () => set((state) => {
      state.creationState = {
        active: false,
        toolType: 'none',
        step: 0,
        tempPoints: [],
        preview: undefined,
      }
    }),

    cancelCreation: () => set((state) => {
      state.creationState = {
        active: false,
        toolType: 'none',
        step: 0,
        tempPoints: [],
        preview: undefined,
      }
    }),

    setRegularPolygonDialog: (updates) => set((state) => {
      state.regularPolygonDialog = { ...state.regularPolygonDialog, ...updates }
    }),

    closeRegularPolygonDialog: () => set((state) => {
      state.regularPolygonDialog = {
        visible: false,
        centerPointId: null,
        radiusPointId: null,
        sides: 3,
      }
    }),

    // History actions
    undo: () => set((state) => {
      if (state.historyIndex > 0) {
        state.historyIndex--
        const snapshot = state.history[state.historyIndex]
        state.expressions = snapshot.expressions
        state.graphPoints = snapshot.graphPoints
        state.images = snapshot.images
        state.drawings = snapshot.drawings
        state.textObjects = snapshot.textObjects
        state.geometryObjects = snapshot.geometryObjects
        state.view = snapshot.view
        state.pages = snapshot.pages
        state.currentPageIndex = snapshot.currentPageIndex
      }
    }),

    redo: () => set((state) => {
      if (state.historyIndex < state.history.length - 1) {
        state.historyIndex++
        const snapshot = state.history[state.historyIndex]
        state.expressions = snapshot.expressions
        state.graphPoints = snapshot.graphPoints
        state.images = snapshot.images
        state.drawings = snapshot.drawings
        state.textObjects = snapshot.textObjects
        state.geometryObjects = snapshot.geometryObjects
        state.view = snapshot.view
        state.pages = snapshot.pages
        state.currentPageIndex = snapshot.currentPageIndex
      }
    }),

    canUndo: () => {
      const state = useStore.getState()
      return state.historyIndex > 0
    },

    canRedo: () => {
      const state = useStore.getState()
      return state.historyIndex < state.history.length - 1
    },

    saveToHistory: () => set((state) => {
      saveHistory(state)
    }),

    // Page management actions
    addPage: () => set((state) => {
      // Save current page state before adding new one
      const currentPage = state.pages[state.currentPageIndex]
      if (currentPage) {
        currentPage.expressions = state.expressions
        currentPage.graphPoints = state.graphPoints
        currentPage.images = state.images
        currentPage.drawings = state.drawings
        currentPage.textObjects = state.textObjects
        currentPage.geometryObjects = state.geometryObjects
        currentPage.view = state.view
      }

      // Create new empty page
      const newPage: Page = {
        id: crypto.randomUUID(),
        name: `페이지 ${state.pages.length + 1}`,
        expressions: [{
          id: crypto.randomUUID(),
          kind: 'cartesian',
          input: '',
          latex: '',
          color: PRESET_COLORS[0],
          visible: true,
          selected: false,
        }],
        graphPoints: [],
        images: [],
        drawings: [],
        textObjects: [],
        geometryObjects: [],
        view: {
          center: { x: 0, y: 0 },
          scale: 50,
          scaleX: 1,
          scaleY: 1,
          grid: true,
          axis: true,
        },
      }

      state.pages.push(newPage)
      state.currentPageIndex = state.pages.length - 1

      // Load new page state
      state.expressions = newPage.expressions
      state.graphPoints = newPage.graphPoints
      state.images = newPage.images
      state.drawings = newPage.drawings
      state.textObjects = newPage.textObjects
      state.geometryObjects = newPage.geometryObjects
      state.view = newPage.view

      // Reset history for new page
      saveHistory(state)
    }),

    removePage: (index: number) => set((state) => {
      if (state.pages.length <= 1) return // Keep at least one page

      state.pages.splice(index, 1)

      // Adjust current page index if needed
      if (state.currentPageIndex >= state.pages.length) {
        state.currentPageIndex = state.pages.length - 1
      } else if (state.currentPageIndex > index) {
        state.currentPageIndex--
      }

      // Load current page state
      const currentPage = state.pages[state.currentPageIndex]
      state.expressions = currentPage.expressions
      state.graphPoints = currentPage.graphPoints
      state.images = currentPage.images
      state.drawings = currentPage.drawings
      state.textObjects = currentPage.textObjects
      state.geometryObjects = currentPage.geometryObjects
      state.view = currentPage.view

      // Reset history
      saveHistory(state)
    }),

    switchPage: (index: number) => set((state) => {
      if (index < 0 || index >= state.pages.length) return
      if (index === state.currentPageIndex) return

      // Save current page state
      const currentPage = state.pages[state.currentPageIndex]
      if (currentPage) {
        currentPage.expressions = state.expressions
        currentPage.graphPoints = state.graphPoints
        currentPage.images = state.images
        currentPage.drawings = state.drawings
        currentPage.textObjects = state.textObjects
        currentPage.geometryObjects = state.geometryObjects
        currentPage.view = state.view
      }

      // Switch to new page
      state.currentPageIndex = index
      const newPage = state.pages[index]

      // Load new page state
      state.expressions = newPage.expressions
      state.graphPoints = newPage.graphPoints
      state.images = newPage.images
      state.drawings = newPage.drawings
      state.textObjects = newPage.textObjects
      state.geometryObjects = newPage.geometryObjects
      state.view = newPage.view

      // Reset history for switched page
      saveHistory(state)
    }),

    updatePageName: (index: number, name: string) => set((state) => {
      if (index >= 0 && index < state.pages.length) {
        state.pages[index].name = name
      }
    }),

    reorderPages: (fromIndex: number, toIndex: number) => set((state) => {
      if (fromIndex < 0 || fromIndex >= state.pages.length) return
      if (toIndex < 0 || toIndex >= state.pages.length) return
      if (fromIndex === toIndex) return

      // Save current page state first
      const currentPage = state.pages[state.currentPageIndex]
      if (currentPage) {
        currentPage.expressions = state.expressions
        currentPage.graphPoints = state.graphPoints
        currentPage.images = state.images
        currentPage.drawings = state.drawings
        currentPage.textObjects = state.textObjects
        currentPage.geometryObjects = state.geometryObjects
        currentPage.view = state.view
      }

      // Remove the page from old position
      const [movedPage] = state.pages.splice(fromIndex, 1)
      // Insert at new position
      state.pages.splice(toIndex, 0, movedPage)

      // Update currentPageIndex to follow the moved page if it was the current one
      if (state.currentPageIndex === fromIndex) {
        state.currentPageIndex = toIndex
      } else if (fromIndex < state.currentPageIndex && toIndex >= state.currentPageIndex) {
        state.currentPageIndex--
      } else if (fromIndex > state.currentPageIndex && toIndex <= state.currentPageIndex) {
        state.currentPageIndex++
      }
    }),

    updatePageThumbnail: (index: number, thumbnail: string) => set((state) => {
      if (index >= 0 && index < state.pages.length) {
        state.pages[index].thumbnail = thumbnail
      }
    }),
  }))
)

/**
 * Try to express number as a simple fraction
 */
function toSimpleFraction(num: number, maxDenominator: number = 12): string | null {
  const sign = num < 0 ? '-' : ''
  const absNum = Math.abs(num)

  // If it's an integer, don't use fraction
  if (Math.abs(absNum - Math.round(absNum)) < 1e-14) {
    return null
  }

  // Try to find a simple fraction (only common denominators)
  for (let denominator = 2; denominator <= maxDenominator; denominator++) {
    const numerator = Math.round(absNum * denominator)
    const fraction = numerator / denominator

    if (Math.abs(fraction - absNum) < 1e-14) {
      // Simplify by finding GCD
      const gcd = (a: number, b: number): number => b === 0 ? a : gcd(b, a % b)
      const divisor = gcd(numerator, denominator)
      const simplifiedNum = numerator / divisor
      const simplifiedDen = denominator / divisor

      if (simplifiedDen === 1) {
        return null // It's actually an integer
      }

      return `${sign}${simplifiedNum}/${simplifiedDen}`
    }
  }

  return null
}

/**
 * Try to recognize special values like π, √2, √3, etc.
 */
function toSymbolicForm(num: number): string | null {
  const absNum = Math.abs(num)
  const sign = num < 0 ? '-' : ''

  // Check for π
  if (Math.abs(absNum - Math.PI) < 1e-10) {
    return `${sign}π`
  }
  if (Math.abs(absNum - 2 * Math.PI) < 1e-10) {
    return `${sign}2π`
  }
  if (Math.abs(absNum - Math.PI / 2) < 1e-10) {
    return `${sign}π/2`
  }
  if (Math.abs(absNum - Math.PI / 3) < 1e-10) {
    return `${sign}π/3`
  }
  if (Math.abs(absNum - Math.PI / 4) < 1e-10) {
    return `${sign}π/4`
  }
  if (Math.abs(absNum - Math.PI / 6) < 1e-10) {
    return `${sign}π/6`
  }

  // Check for common square roots
  const commonRoots = [2, 3, 5, 6, 7, 10]
  for (const n of commonRoots) {
    if (Math.abs(absNum - Math.sqrt(n)) < 1e-10) {
      return `${sign}√${n}`
    }
    // Check for multiples of square roots
    for (let mult = 2; mult <= 5; mult++) {
      if (Math.abs(absNum - mult * Math.sqrt(n)) < 1e-10) {
        return `${sign}${mult}√${n}`
      }
    }
    // Check for fractions of square roots
    for (let denom = 2; denom <= 4; denom++) {
      if (Math.abs(absNum - Math.sqrt(n) / denom) < 1e-10) {
        return `${sign}√${n}/${denom}`
      }
    }
  }

  // Check for e
  if (Math.abs(absNum - Math.E) < 1e-10) {
    return `${sign}e`
  }

  return null
}

/**
 * Snap a value to special mathematical values if it's close enough
 * Returns the exact special value if close, otherwise returns the original value
 */
function snapToSpecialValue(num: number): number {
  console.log('snapToSpecialValue input:', num)
  const tolerance = 1e-3  // Tolerance for snapping to special values
  const absNum = Math.abs(num)
  const sign = num < 0 ? -1 : 1

  // Check for zero
  if (Math.abs(num) < tolerance) {
    console.log('  Snapped to 0')
    return 0
  }

  // Check for integers (within tolerance)
  const nearestInt = Math.round(num)
  if (Math.abs(num - nearestInt) < tolerance) {
    console.log(`  Snapped to integer: ${nearestInt}`)
    return nearestInt
  }

  // Check for integer multiples of π
  for (let mult = 1; mult <= 10; mult++) {
    if (Math.abs(absNum - mult * Math.PI) < tolerance) {
      console.log(`  Snapped to ${sign * mult}π`)
      return sign * mult * Math.PI
    }
  }

  // Check common fractions of π
  const piDenominators = [2, 3, 4, 6, 8, 12]
  for (const denom of piDenominators) {
    for (let numer = 1; numer < denom * 4; numer++) {
      const value = (numer * Math.PI) / denom
      if (Math.abs(absNum - value) < tolerance) {
        return sign * value
      }
    }
  }

  // Check for common square roots and their multiples
  const commonRoots = [2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]
  for (const n of commonRoots) {
    const sqrtN = Math.sqrt(n)

    // Check for √n
    if (Math.abs(absNum - sqrtN) < tolerance) {
      console.log(`  Snapped to √${n}`)
      return sign * sqrtN
    }

    // Check for multiples: 2√n, 3√n, etc.
    for (let mult = 2; mult <= 10; mult++) {
      if (Math.abs(absNum - mult * sqrtN) < tolerance) {
        console.log(`  Snapped to ${mult}√${n}`)
        return sign * mult * sqrtN
      }
    }

    // Check for fractions: √n/2, √n/3, etc.
    for (let denom = 2; denom <= 10; denom++) {
      if (Math.abs(absNum - sqrtN / denom) < tolerance) {
        console.log(`  Snapped to √${n}/${denom}`)
        return sign * sqrtN / denom
      }
    }
  }

  // Check for e
  if (Math.abs(absNum - Math.E) < tolerance) {
    return sign * Math.E
  }

  // Check for simple fractions
  for (let denom = 2; denom <= 20; denom++) {
    for (let numer = 1; numer < denom * 3; numer++) {
      const value = numer / denom
      if (Math.abs(absNum - value) < tolerance) {
        return sign * value
      }
    }
  }

  // Return original value if no special value is close
  console.log('  No snap, returning original:', num)
  return num
}

/**
 * Format coordinate with appropriate precision
 */
function formatCoord(num: number): string {
  // If very close to an integer, show as integer
  if (Math.abs(num - Math.round(num)) < 1e-10) {
    return Math.round(num).toString()
  }

  // Try symbolic form first
  const symbolic = toSymbolicForm(num)
  if (symbolic) {
    return symbolic
  }

  // Try simple fraction
  const fraction = toSimpleFraction(num)
  if (fraction) {
    return fraction
  }

  // Otherwise show with appropriate decimal places (max 2 decimal places)
  return num.toFixed(2)
}

/**
 * Format coordinate as LaTeX
 */
export function formatCoordLatex(num: number): string {
  console.log('formatCoordLatex input:', num)

  const absNum = Math.abs(num)
  const sign = num < 0 ? '-' : ''
  // Very strict tolerance - only match if within ~14 decimal places
  const tolerance = 1e-14

  // If very close to an integer, show as integer
  if (Math.abs(num - Math.round(num)) < tolerance) {
    console.log('  Formatted as integer:', Math.round(num))
    return Math.round(num).toString()
  }

  // Check for π multiples and fractions - very strict
  const piTolerance = tolerance

  // Check integer multiples of π first (0π, 1π, 2π, 3π, etc.)
  for (let mult = 1; mult <= 10; mult++) {
    if (Math.abs(absNum - mult * Math.PI) < piTolerance) {
      if (mult === 1) {
        return `${sign}\\pi`
      }
      return `${sign}${mult}\\pi`
    }
  }

  // Check common fractions of π
  const piDenominators = [2, 3, 4, 6, 8, 12]
  for (const denom of piDenominators) {
    for (let numer = 1; numer < denom * 4; numer++) {
      const value = (numer * Math.PI) / denom
      if (Math.abs(absNum - value) < piTolerance) {
        // Simplify the fraction
        const gcd = (a: number, b: number): number => b === 0 ? a : gcd(b, a % b)
        const divisor = gcd(numer, denom)
        const simplifiedNumer = numer / divisor
        const simplifiedDenom = denom / divisor

        if (simplifiedDenom === 1) {
          if (simplifiedNumer === 1) {
            return `${sign}\\pi`
          }
          return `${sign}${simplifiedNumer}\\pi`
        }
        if (simplifiedNumer === 1) {
          return `${sign}\\frac{\\pi}{${simplifiedDenom}}`
        }
        return `${sign}\\frac{${simplifiedNumer}\\pi}{${simplifiedDenom}}`
      }
    }
  }

  // Check for common square roots
  const commonRoots = [2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]
  for (const n of commonRoots) {
    const sqrtN = Math.sqrt(n)

    // Check for √n
    if (Math.abs(absNum - sqrtN) < tolerance) {
      return `${sign}\\sqrt{${n}}`
    }

    // Check for multiples: 2√n, 3√n, etc.
    for (let mult = 2; mult <= 10; mult++) {
      if (Math.abs(absNum - mult * sqrtN) < tolerance) {
        return `${sign}${mult}\\sqrt{${n}}`
      }
    }

    // Check for fractions: √n/2, √n/3, etc.
    for (let denom = 2; denom <= 10; denom++) {
      if (Math.abs(absNum - sqrtN / denom) < tolerance) {
        return `${sign}\\frac{\\sqrt{${n}}}{${denom}}`
      }
    }
  }

  // Check for e
  if (Math.abs(absNum - Math.E) < 1e-10) {
    return `${sign}e`
  }

  // Try simple fraction
  const fraction = toSimpleFraction(num)
  if (fraction) {
    // Convert "a/b" to "\frac{a}{b}"
    const match = fraction.match(/^(-?)(\d+)\/(\d+)$/)
    if (match) {
      const [, minusSign, numerator, denominator] = match
      return `${minusSign}\\frac{${numerator}}{${denominator}}`
    }
  }

  // Otherwise show with appropriate decimal places (max 2 decimal places)
  return num.toFixed(2)
}

/**
 * Save current state to history
 */
// Debounce timer for saveHistory
let saveHistoryTimer: ReturnType<typeof setTimeout> | null = null
let pendingState: AppState | null = null

function saveHistoryImmediate(state: AppState) {
  // Remove any history after current index (when undoing and then making new changes)
  state.history = state.history.slice(0, state.historyIndex + 1)

  // Deep copy via JSON to safely clone Immer draft/Proxy objects
  // Only clone current page data (not all pages' content) for memory efficiency
  const clone = (obj: any) => JSON.parse(JSON.stringify(obj))
  const snapshot: HistoryState = {
    expressions: clone(state.expressions),
    graphPoints: clone(state.graphPoints),
    images: clone(state.images),
    drawings: clone(state.drawings),
    textObjects: clone(state.textObjects),
    geometryObjects: clone(state.geometryObjects),
    view: clone(state.view),
    pages: state.pages.map(p => ({ id: p.id, name: p.name, thumbnail: p.thumbnail })) as any,
    currentPageIndex: state.currentPageIndex,
  }

  // Add to history
  state.history.push(snapshot)
  state.historyIndex = state.history.length - 1

  // Limit history to 30 steps to reduce memory usage
  const MAX_HISTORY = 30
  if (state.history.length > MAX_HISTORY) {
    state.history.shift()
    state.historyIndex--
  }
}

function saveHistory(state: AppState) {
  // For high-frequency operations, debounce to avoid excessive snapshots
  saveHistoryImmediate(state)
}

/**
 * Convert index to label (A, B, C, ..., Z, AA, AB, ...)
 */
function indexToLabel(index: number): string {
  let label = ''
  let num = index

  do {
    label = String.fromCharCode(65 + (num % 26)) + label
    num = Math.floor(num / 26) - 1
  } while (num >= 0)

  return label
}
